server:
  port: 8081
spring:
  application:
    name: Local Review Deal System
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Local_Review_Deal_System?useSSL=false&serverTimezone=UTC
    username: root
    password: localhost
  redis:
    host: localhost
    port: 6379
    password: 123321
    #连接池配置
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.local_review_deal_sys.entity # 别名扫描包
logging:
  level:
    com.local_review_deal_sys: debug